### ISSUE TITLE
Custom datasets and location specifications in metrics module

### ISSUE THREAD

**Issue by ttaa9** [kwotsin/mimicry#20]
I was wondering if it were possible to add an interface to the `metrics.evaluate` interface for the following:

1. Custom datasets: being able to pass a `dataloader` argument instead of `dataset_name` would let us use the same function for new/custom data.

2. Location: similar to how `datasets. load_dataset` has a `root` argument, it would be nice if `metrics.evaluate` offered the same functionality to choose where to place the data.

Apologies if these are already present somewhere. Thanks again for a very nice library.

**Comment by kwotsin** [comment]
Hi @ttaa9 thanks a lot for the great suggestions!! Indeed I think there are quite a few constraints currently and I'm planning to make it more flexible for custom uses. I will work on them soon and keep you updated! 

*Note: current response/work is delayed due to COVID circumstances (no access to computing resources).*

**Comment by kwotsin** [comment]
Hi @ttaa9, I have improved the metrics usage to allow for a custom dataset to be used during evaluation. I have also included an example script of how to use this at: https://github.com/kwotsin/mimicry/blob/master/examples/eval_pretrained.py

To install the latest changes, simply pip upgrade to v0.1.14 or install the master version of the git branch with `pip install git+https://github.com/kwotsin/mimicry.git`.

Please feel free to let me know if it's working fine -- will close the issue for now!
