### ISSUE TITLE
Plans on adding SAGAN?

### ISSUE THREAD

**Issue by nivha** [kwotsin/mimicry#3]
Great repository! any plans on adding SAGAN (https://arxiv.org/pdf/1805.08318.pdf)?
Thanks

**Comment by kwotsin** [comment]
Yes indeed! It's one of the GANs I'm considering to add in the future, will keep this issue open and update it when it's done!

**Comment by zhangmozhe** [comment]
Also Biggan if possible?

**Comment by kwotsin** [comment]
@zhangmozhe Thanks for the suggestion! I'll look into BigGAN as well although I might not have enough resources to train it using the hyperparameters suggested (will check again)

**Comment by nivha** [comment]
@zhangmozhe in the case of BigGAN there's an ["official unofficial" pytorch implementation](https://github.com/ajbrock/BigGAN-PyTorch)  by the authors written for reproducing their results

**Comment by kwotsin** [comment]
Hi everyone, I've implemented SAGAN (https://github.com/kwotsin/mimicry/blob/master/torch_mimicry/nets/sagan/sagan_128.py) but it seems since the original paper only trained on imagenet 128x128 that requires about 2 months to train using 1 GPU (1M iterations), I might not have the resources to reasonably train it on time. However, I provided the implementation in the master branch which you can install to check it out, and if you have the resources to train the model, please feel free to share the checkpoint weights!

I also included an extra 32x32 version of SAGAN which I think is easier to train, although of course the implementation is "unofficial" since the placement of the self-attention block may not be optimal, and there's no reference implementation.

Will keep this issue closed for now but will update/reopen if there are any changes. Thanks everyone!
