### ISSUE TITLE
How to judge the training process is correct

### ISSUE THREAD

**Issue by czzerone** [kwotsin/mimicry#34]
Thanks for your code! I am trying to add a new module to the SNGAN model, but I don't know how to judge my model is correct during the training since it's not like the classification task which can use the loss function to judge if the classifier is trained well. Can you give me some advice on it? thanks!

**Comment by kwotsin** [comment]
Hi @czzerone, it is quite difficult to judge how well the training is going in terms of losses usually, since depending on what loss you use (hinge loss, wasserstein loss etc.), the curves can look *very* different.

That said, I think a few approaches might help:
1. Do a visual analysis of the output: TensorBoard visualisations from the training can tell you whether the generator has mode collapsed.
2. Losses go very flat or diverges (but quite subjective still depending on which loss you used). If you're interested, you can train the base SNGAN model to see how the loss should look like. That can be a reference point to see if your new addition works.

Hope this helps and happy researching!
