### ISSUE TITLE
Could you add the SAGAN for 256x256 size image?

### ISSUE THREAD

**Issue by 25th-engineer** [kwotsin/mimicry#36]
I'm trying to implement the self-attention for 256x256 size image but it didn't work well.
I've tried many times.
Thanks in advance.

**Comment by XiaoBuL** [comment]
Perhaps you should change the spectral linear input size.

**Comment by kwotsin** [comment]
@25th-engineer Unfortunately I currently have no plans to add SAGAN as the literature has since moved on a little, and I no longer have access to GPU machines to run my experiments. That said, I tried implementing SAGAN on smaller datasets initially, but the results doesn't seem to be as good so I think if you try that, probably larger datasets might work better.

**Comment by 25th-engineer** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你发送的电子邮件我已经收到。
