### ISSUE TITLE
Where is `losses.ns_loss_dis`?

### ISSUE THREAD

**Issue by stephenllh** [kwotsin/mimicry#6]

**Comment by kwotsin** [comment]
Hi @stephenllh, `ns_loss_dis` doesn't exist since the non-saturating loss is for the generator instead! when the NS loss formulation is used for GAN, the same minimax loss is used except generator loss is switched to a non-saturating one, see: https://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf
