### ISSUE TITLE
Metrics computation proposal

### ISSUE THREAD

**Issue by toshas** [kwotsin/mimicry#7]
Would maintainers consider switching to https://github.com/toshas/torch-fidelity for Inception-induced score/metrics?

**Comment by kwotsin** [comment]
Hi @toshas, thanks for the proposal! Currently there are no plans to switch the metrics yet, as I'm hoping to use the original implementations to produce new scores that are backward compatible to old scores. This is also since interestingly [1] observed that the metrics can be sensitive to weight differences and the inception model used in the TF version has several pecularities (footnote 2 in [1]). However, your work looks great and I think it will contribute to the options available for researchers -- great work done!

[1] https://arxiv.org/pdf/1801.01973.pdf

**Comment by toshas** [comment]
Sorry for the late reply. If you check out the readme of torch-fidelity repo, you will find out the way all sources of non-determinism were accounted for in a pure pytorch implementation.
